version: '3'
services:
  my-node:
    image: zankorrr/home-service
    container_name: server
    build: .
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - my-postgres
    environment:
      - PORT=${PORT}
    restart: always
    volumes:
      - data:/data/app
    networks:
      - home-service-network
    command: npm run start:dev
  my-postgres:
    image: zankorrr/home-service-database
    container_name: database
    build: ./prisma
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    volumes:
      - db:/data/db
    networks:
      - home-service-network
    command: postgres -c logging_collector=on
volumes:
  data:
    name: app
  db:
    name: db
networks:
  home-service-network:
    name: home-service-network